### ISSUE TITLE
Duplicate key

### ISSUE THREAD

**Issue by slonob** [counteractive/security-controls#1]
In data/controls.csv, this:
{"source":"cis_csc_v7.1","id":"cis_csc_v7.1:12.10","id_raw":"**12.1**","tier_raw":"Sub-Control","tier":"1","seq":"84","title":"Decrypt Network Traffic at Proxy","description":"Decrypt all encrypted network traffic at the boundary proxy prior to analyzing the content. However, the organization may use whitelists of allowed sites that can be accessed through the proxy without decrypting the traffic."},
 
Should be:
{"source":"cis_csc_v7.1","id":"**cis_csc_v7.1:12.10**","id_raw":"**12.10**","tier_raw":"Sub-Control","tier":"1","seq":"84","title":"Decrypt Network Traffic at Proxy","description":"Decrypt all encrypted network traffic at the boundary proxy prior to analyzing the content. However, the organization may use whitelists of allowed sites that can be accessed through the proxy without decrypting the traffic."},

-Jarrod

**Comment by lostbutlearning** [comment]
Quite right, Jarrod, thank you for filing the issue!  Found a few others that were missing trailing zeroes as well.  Fixed in 2c16691.

**Comment by chris-counteractive** [comment]
Quite right, Jarrod, thank you for filing the issue! Found a few others that were missing trailing zeroes as well. Fixed in 2c16691.

**Comment by slonob** [comment]
Also: 
{"source":"cis_csc_v7.1","id":"cis_csc_v7.1:7.10","id_raw":"**7.1**","tier_raw":"Sub-Control","tier":"1","seq":"49","title":"Sandbox All Email Attachments","description":"Use sandboxing to analyze and block inbound email attachments with malicious behavior."},

Should be:
{"source":"cis_csc_v7.1","id":"cis_csc_v7.1:7.10","id_raw":"7.1","tier_raw":"Sub-Control","tier":"1","seq":"49","title":"Sandbox All Email Attachments","description":"Use sandboxing to analyze and block inbound email attachments with malicious behavior."},

**Comment by chris-counteractive** [comment]
Yessir - there were 6 others I found and fixed, the one you just mentioned shows corrected [here in the CSV](https://github.com/counteractive/security-controls/blob/master/data/controls.csv#L169) and [here in the JSON](https://github.com/counteractive/security-controls/blob/master/data/controls.json#L172).  Thanks again!
